version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-and-test:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/client
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    machine:
      enabled: true
    working_directory: ~/client
    steps:
      - add_ssh_keys:
          fingerprints:
            - "aa:75:ea:fb:35:1c:a3:4a:04:75:56:40:8f:ae:02:49"
      - checkout
      - run:
          name: Push Master to Production
          command: git push https://github.com/d0ugr/scheduler.git master:production

workflows:
  deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build-and-test



# Original:

# version: 2.1
# orbs:
#   node: circleci/node@1.1.6
# jobs:
#   build-and-test:
#     executor:
#       name: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: npm install
#             - run: npm test
# workflows:
#     build-and-test:
#       jobs:
#         - build-and-test
