// DayListItem.js
//
// React component that shows a day in the sidebar.
//    These are generated by the DayList component.

import React      from "react";
import classNames from "classnames";

import "./DayListItem.scss";

// DayListItem component definition.
//
//    props.name       String:   Day name (e.g. Caturday).
//    props.spots      String:   Number of appointment timeslots available.
//    props.selected   Boolean:  Whether or not this day is selected in the sidebar.
//    props.setDay     Function: Callback that selects the day when it is clicked.

const formatSpots = function(spots) {
  return (
    !spots || (spots === 0)
    ? "no spots remaining"
    : `${spots} spot${spots === 1 ? "" : "s"} remaining`
  );
};

export default function DayListItem(props) {

  const dayListItemClasses = classNames("day-list__item", {
    "day-list__item--selected": props.selected,
    "day-list__item--full":     props.spots === 0
  });

  return (
    <li
      className={dayListItemClasses}
      onClick={props.setDay}
      data-testid="day"
    >
      <h2 className="text--regular">{props.name}</h2>
      <h3 className="text--light">{formatSpots(props.spots)}</h3>
    </li>
  );

}
